export default [
  {
    errorText: 'Please enter the name of your job title.',
    required: true,
    label: 'Title',
    type: 'text',
    name: 'title',
    multiLine: false,
    order: 1,
  },
  {
    errorText: '',
    required: true,
    label: 'Location',
    type: 'text',
    name: 'location',
    multiLine: false,
    order: 2,
  },
  {
    errorText: '',
    required: false,
    label: 'From Date',
    type: 'date',
    name: 'fromDate',
    order: 3,
  },
  {
    errorText: '',
    required: false,
    label: 'To Date',
    type: 'date',
    name: 'toDate',
    order: 4,
  },
  {
    errorText: '',
    required: false,
    label: 'Description',
    type: 'text',
    name: 'description',
    multiLine: true,
    order: 6,
  },
  {
    errorText: '',
    required: false,
    label: 'Current position',
    type: 'toggle',
    name: 'currentPosition',
    order: 5,
  },
];
