import dataService from '../../services/data';

export default [
  {
    errorText: 'Please enter the name of the school you visited.',
    required: true,
    label: 'School',
    type: 'text',
    name: 'schoolName',
    multiLine: false,
    order: 1,
  },
  {
    errorText: '',
    required: false,
    label: 'Degree',
    type: 'select',
    options: dataService.getDegrees(),
    name: 'degree',
    order: 2,
  },
  {
    errorText: 'bla bla wrong',
    required: true,
    label: 'Field of Study',
    type: 'text',
    name: 'fieldOfStudy',
    multiLine: false,
    order: 3,
  },
  {
    errorText: '',
    required: false,
    label: 'Grade',
    type: 'text',
    name: 'grade',
    multiLine: false,
    order: 4,
  },
  {
    errorText: '',
    required: false,
    label: 'Form Date',
    type: 'date',
    name: 'fromDate',
    order: 5,
  },
  {
    errorText: '',
    required: false,
    label: 'To Date',
    type: 'date',
    name: 'toDate',
    order: 6,
  },
  {
    errorText: '',
    required: false,
    label: 'Description',
    type: 'text',
    name: 'description',
    multiLine: true,
    rows: 8,
    order: 7,
  },
];
